name: logger
description: Simple logging library for Flutter applications.
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  intl: any
  meta: any
  stack_trace: ^1.12.1
